### ISSUE TITLE
hmpd_analysis_features() compatible with octave?

### ISSUE THREAD

**Issue by dresen** [covarep/covarep#58]
I am trying to run the COVAREP_feature_extraction.m script using octave3.8.2 and I am especially interested in the PDM and PDD. However, the script fails when calling hmpd_analysis_features(). Is this function not compatible with octave?

I have built octave3.8.2 from source on Ubuntu server 12.04 and used pkg to install optim1.4.1, optiminterp0.3.4, tsa4.2.9 and signal1.3.2, but I get similar results on ubuntu server 14.04 where everything is installer via apt-get. 

-Andreas

**Comment by gillesdegottex** [comment]
Hello Andreas!

I don't see any compatibility statement for Octave in hmpd_analysis_features.m so I suppose you're the first to try running it on Octave :)

I cannot test it on my side right now, but I should be able by the week-end.

In the meantime, could you post the error log and, if possible, make the used sound file available to me ?

Keep in touch, Cheers,

**Comment by dresen** [comment]
Using HOWTO_hmpd the function terminates as expected. When I try using my own sound file, an error about the arguments of medfilt1() in vocoder/hmpd/private/hmpd_phase_smooth.m appears. 

Error log:

octave:4> HOWTO_hmpd 
warning: fopen: file found in load path
HMPD Vocoder: Harmonic analysis ...
    No f0 provided in arguments, estimate it using SRH ...
Sample rate not equal to 16kHz. Audio is resampled.

    Estimation of sinusoidal parameters ...
    Adapt analysis instants to f0 curve with 4 analysis intants per period
HMPD Vocoder: Features computation ...
    Estimate amplitude envelope ...
    Estimate phase envelope ...
    Compute phase statistics ...
error: Invalid call to medfilt1.  Correct usage is:

 -- Loadable Function: Y = medfilt1 (X)
 -- Loadable Function: Y = medfilt1 (X, N)
 
error: called from:
error:   /usr/local/share/octave/3.8.2/m/help/print_usage.m at line 89, column 5
error:   /srv/tools/covarep/vocoder/hmpd/private/hmpd_phase_smooth.m at line 64, column 9
error:   /srv/tools/covarep/vocoder/hmpd/hmpd_analysis_features.m at line 71, column 13
error:   /srv/tools/covarep/vocoder/hmpd/hmpd_analysis.m at line 117, column 21
error:   /srv/tools/covarep/howtos/HOWTO_hmpd.m at line 45, column 17
octave:4> 

http://octave.sourceforge.net/signal/function/medfilt1.html

The octave version uses fewer arguments than the matlab equivalent it seems.

The sound file can be accessed here: https://dl.dropboxusercontent.com/u/437646/u0483002_16b.wav

**Comment by gillesdegottex** [comment]
In vocoder/hmpd/private/hmpd_phase_smooth.m:64-65, could you replace the lines by:
    PDc = medfilt1(PDc, winlen);
    PDs = medfilt1(PDs, winlen);
(drop the last two arguments)

and tell me how is it ?

**Comment by dresen** [comment]
It seems to do the trick at first, but the output from COVAREP_feature_extraction.m has changed. I have pasted the first couple of lines below.

I can't get the number of columns to agree with the features and the features are not a single value anymore.

-Andreas

Output

# Created by Octave 3.8.2, Wed Jun 24 12:33:14 2015 CEST <ask@compute4>
# name: features
# type: complex matrix
# rows: 518
# columns: 74
 (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (-10.2583208941557,0) (0.7154630213224061,2.243560591041865e-17) (0.436022803386248,7.196558208549298e-19) (0.6504038089431468,1.163987479595711e-17) (0.2700994149350171,1.726076464785205e-19) (0.1732158771517495,1.843941878873813e-17) (0.3385351949718834,1.340328306867529e-18) (0.3541638687576661,2.090766240399487e-17) (0.01621348368750253,-4.305213841357318e-19) (0.07861533183110159,1.291612508679141e-17) (-0.06355335732293065,3.923165606497586e-19) (-0.1091459873916788,1.677020333894164e-17) (0.02481693481314957,-4.067005311896353e-19) (0.0752261078321986,9.529981701817855e-18) (-0.06010518628017211,1.173156221510652e-18) (-0.09762363629635974,9.663151282815735e-18) (-0.05252250952364,-3.517836956891235e-19) (0.05847573319160199,2.273464661560267e-18) (0.003656042742806009,8.156043873463616e-19) (0.02763021078721398,5.624862003649595e-18) (0.02391523094423336,-1.358245911788589e-18) (0.01279232660126643,7.094390589220546e-18) (-0.08154763812583427,-1.151507514404754e-18) (0.04970196789165525,7.365534768259572e-18) (-0.01103989013190091,-1.995464121138965e-19) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0)
 (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (-10.22438306604608,0) (0.6326334220380992,2.270197045890799e-17) (0.3467200011189771,3.414575744443677e-19) (0.7058341363899574,1.208290433324242e-17) (0.293376674736427,9.427270109538594e-19) (0.1276955292538891,1.690396795693177e-17) (0.269290958592465,6.320105346927697e-19) (0.2183353238577597,1.984040393232049e-17) (-0.07080340005241356,-1.331287881001637e-19) (6.309113190152218e-05,1.270741244473209e-17) (-0.04191286461065606,-5.342505369755172e-20) (-0.0732899272359452,1.129255212479344e-17) (-0.01836098658933854,-7.235727303569418e-19) (0.01844226479582566,9.233289577900707e-18) (0.05042892188898822,-2.681582354966053e-19) (-0.02383457793382685,8.14314202263003e-18) (0.006375595330585734,-7.453889935837843e-20) (-0.028193482544924,1.422263768986638e-18) (-0.008189154691208046,-1.391613154318286e-19) (0.05011423870851387,5.118383833144219e-18) (-0.02747521769129222,-7.959630583369191e-19) (0.004258031347232412,4.662589205581431e-18) (-0.03666213385070302,-1.221049641817516e-18) (0.05299818134519956,8.989324055280876e-18) (-0.00981282299700946,-2.373344999526196e-19) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0) (0,0)

**Comment by gillesdegottex** [comment]
Ok, medfilt1 on Octave and Matlab might zeropad differently, I'll go into this by the week-end.

**Comment by dresen** [comment]
After doing some more testing, I found out that saving HMPDD to file changes the output because each cell is a number +/- a complex or imaginary number (0.00000i). So a row from HMPDD would look like this:

0.95272 -  0.00000i    0.85460 -  0.00000i    0.78502 -  0.00000i    0.24860 +  0.00000i    0.03475 -  0.00000i   -0.32382 +  0.00000i

Hope it helps

-Andreas

**Comment by gillesdegottex** [comment]
I fixed one or two limit cases where -0 values were appearing, thus, creating complex values.
You can download the master version to try.

Now, I can process both the demonstration sample and your sample under Octave.
For your sample, the f0 range has to be setup properly.

I'm so sorry, but the whole analysis is sooooooooooo slow on Octave ...
The problem is that the profiler is lacking an interface and I'm not able to track what is so slow.

Tell me how it goes on your side.

Cheers,
Gilles

**Comment by dresen** [comment]
Hi Gilles

I still see the same problem:

octave:63> HMPDD(1,:)
ans =

 Columns 1 through 4:

  -14.03919 +  0.00000i    2.25563 -  0.00000i    1.73155 +  0.00000i    0.82269 -  0.00000i

 Columns 5 through 8:

    0.55844 -  0.00000i    1.14210 -  0.00000i    0.42234 -  0.00000i    0.40288 +  0.00000i

 Columns 9 through 12:

    0.27243 +  0.00000i    0.13250 +  0.00000i    0.50349 -  0.00000i    0.73298 +  0.00000i

 Column 13:

    0.10515 -  0.00000i

octave:64> 

I did a fresh git clone to be sure I had the right version from the master branch with your changes.

I executed the commands manually and found that hmpd_compress_features.m outputs matrices with cells that contain imaginary numbers for both AEC and PDDC:

octave:117> AEC(1,:)
ans =

 Columns 1 through 4:

  -13.13321 +  0.00000i    0.85631 -  0.00000i    0.22388 +  0.00000i    0.39112 -  0.00000i

 Columns 5 through 8:

    0.01331 +  0.00000i    0.23915 -  0.00000i    0.11480 +  0.00000i    0.25510 -  0.00000i

 Columns 9 through 12:

    0.01113 -  0.00000i    0.24667 -  0.00000i   -0.05268 +  0.00000i   -0.16570 -  0.00000i

 Columns 13 through 16:

   -0.07530 -  0.00000i    0.13082 -  0.00000i   -0.16405 +  0.00000i   -0.24374 -  0.00000i

 Columns 17 through 20:

   -0.09039 +  0.00000i   -0.00249 +  0.00000i    0.01178 +  0.00000i   -0.05323 +  0.00000i

 Columns 21 through 24:

    0.21294 -  0.00000i    0.19288 -  0.00000i   -0.07870 +  0.00000i   -0.12025 -  0.00000i

 Columns 25 through 28:

    0.11801 -  0.00000i   -0.04861 -  0.00000i   -0.05573 +  0.00000i   -0.01450 -  0.00000i

 Columns 29 through 32:

    0.11479 +  0.00000i   -0.04272 -  0.00000i   -0.04390 +  0.00000i    0.03713 +  0.00000i

 Columns 33 through 36:

    0.01920 -  0.00000i   -0.01622 -  0.00000i   -0.08856 -  0.00000i    0.17111 +  0.00000i

 Columns 37 through 40:

   -0.06335 +  0.00000i   -0.05115 -  0.00000i    0.01154 +  0.00000i    0.02196 -  0.00000i

octave:118> PDDC(1,:)
ans =

 Columns 1 through 4:

  -13.69185 +  0.00000i    1.95956 -  0.00000i    1.48966 -  0.00000i    1.38471 -  0.00000i

 Columns 5 through 8:

    0.97211 -  0.00000i    0.88364 -  0.00000i    0.02597 +  0.00000i    0.87115 -  0.00000i

 Columns 9 through 12:

    0.18811 -  0.00000i   -0.32698 -  0.00000i   -0.46476 +  0.00000i   -0.38259 -  0.00000i

 Column 13:

    1.00585 -  0.00000i

octave:119> 


Also, what did you set the f0 range to?


Cheers,

-Andreas

**Comment by gillesdegottex** [comment]
I used f0 in [100; 400] as far as I remember.

What's your Octave version ? I have 3.8.1

Is it possible for your to zip your whole working directory, with the sound example, all the code, etc. to see if I can reproduce this bug ?

Cheers,
G

**Comment by dresen** [comment]
You can download my zipped covarep from https://dl.dropboxusercontent.com/u/437646/covarep.gz

I used Octave 3.8.2. I tried downgrading Octave to 3.8.1, but I got the same results.  What versions of optim, tsa and signal do you use? I built both versions from source on Ubuntu server 12.04 and installed optim1.4.1, optiminterp0.3.4, tsa4.2.9 and signal1.3.2 using Octaves pkg command.

**Comment by gillesdegottex** [comment]
On my side:
octave-optim: 1.3.0
octave-optiminterp: 0.3.4
octave-tsa: 4.2.7
octave-signal: 1.2.2

Well that's might make a difference, but all your versions are higher than mine. Thus, if it passes on my side and not on yours, it's because a bug as been fixed in your version ...

(thanks for the pkg, checking it asap)

**Comment by gillesdegottex** [comment]
what's the compression format of the package ? I can gunzip it but I don't know what to do with the resulting file.
Could you make a tar.gz or a zip ?

**Comment by dresen** [comment]
Here's a new link: https://dl.dropboxusercontent.com/u/437646/covarep.tar.gz

**Comment by gillesdegottex** [comment]
and what's the exact command that your run ?

**Comment by dresen** [comment]
tar -czf covarep.tar.gz covarep

**Comment by dresen** [comment]
for the second package

**Comment by gillesdegottex** [comment]
Sorry,  I meant once it is decompressed, what's the octave command that you run.

**Comment by dresen** [comment]
first startup, then COVAREP_feature_extraction('one')

**Comment by gillesdegottex** [comment]
I can reproduce it :)
Investigating .....

**Comment by gillesdegottex** [comment]
There was a lack of numerical precision during the ifft.
Fixed. Please checkout the master.

Cheers

**Comment by dresen** [comment]
I haven't tested with the newest octave packages (it seems the leap second knocked out our servers...), but I have an external server with the same packages as you and it works here too. 

Thanks a lot for your time and help!!

**Comment by gillesdegottex** [comment]
Great ! Feel free to recontact for anything else.
Cheers
